### PR TITLE
Add Harun bio

### LINKED ISSUE #3: Introduce Harun
**As a site visitor, I want to learn more about Harun**

## Repo
- [x] developed on a branch named `harun`  

## harun.md
- [x] create the file
- [x] add their name as the main title
- [x] write a paragraph introduction
- [x] create a link back to the README
 
## README.md
- [x] change their name list on README.md into a link

### PR DESCRIPTION
**Pull request by adekimpianna**
Created Harun file and added link to his name on readme.md file

closes #3

### CODE REVIEW

**Review by snicoll — APPROVED** [review]
Nitpicking but a line has been removed at the end. Probably your editor did it so no need to act on it :)

**Comment by adekimpianna** [comment]
@snicoll yeah, I did not understand why that empty lined was removed.

Okay guys... so now there is a conflict, because miroslav.md file has been already merged.  
I will resolve the conflict.

**Review by harunaltunhr — COMMENTED** [review]
Goed

**Review by harunaltunhr — APPROVED** [review]

**Review by miroslavveljanoski — APPROVED** [review]

**Comment by miroslavveljanoski** [comment]
This seems great to me. Since most of you approved these changes I'm going to merge this pull request.

**Pull request merged**
