### PR TITLE
Add bio for Boam

### LINKED ISSUE #9: Introduce Boam
## 5. Introduce Boam

__As a site visitor, I want to learn more about Boam__

> assigned to Miroslav

### Repo

- [x] developed on a branch named `boam`

### boam.md

- [x] create the file
- [x] add their name as the main title
- [x] write a paragraph introduction
- [x] create a link back to the README

### README.md

- [x] change their list item into a link

---

### PR DESCRIPTION
**Pull request by miroslavveljanoski**
Hi guys. I made the bio for Boam. Please review my code and if everyone agrees we can merge it to the master 
Closes #9

### CODE REVIEW

**Comment by miroslavveljanoski** [comment]
There is a conflict because in my readme file I didn't have the links to Miroslav, Yana and Murielle. Before I push my branch `boam`, I checkout master and pull the newest version from github. Maybe instead of "pull" I should have done "rebase"? Otherways there will always conflict like this probably? I'm doing something wrong?

**Comment by snicoll** [comment]
Thanks for asking. As a good team member, resolving the conflict yourself is indeed the way to go. First, make sure you have all the changes from the server, then you need to rebase your branch to master and resolve the conflict locally:

```
git fetch
git rebase origin/master
```

You’ll have to fix the conflict on your machine. Once you’re done you can update this pull request by pushing again. Since you’ve rebased, you’ve modified the history so you need to use the `—force` option. Let me know if you need help with that.

**Comment by miroslavveljanoski** [comment]
> Thanks for asking. As a good team member, resolving the conflict yourself is indeed the way to go. First, make sure you have all the changes from the server, then you need to rebase your branch to master and resolve the conflict locally:
> 
> ```
> git fetch
> git rebase origin/master
> ```
> 
> You’ll have to fix the conflict on your machine. Once you’re done you can update this pull request by pushing again. Since you’ve rebased, you’ve modified the history so you need to use the `—force` option. Let me know if you need help with that.

@snicoll I did try but nothing :worried: . I checkout to my branch `boam` and as you advise first I write `git fetch` then `git rebase origin/master`. After that I pushed again my branch with the command `git push --force origin boam` and still nothing. I'm really confused with this :confused:

**Comment by harunaltunhr** [comment]
It looks true. After everybody agree, we will merge

**Comment by snicoll** [comment]
Let’s not merge this one yet and I’ll help miroslav this week

**Comment by miroslavveljanoski** [comment]
Somehow I manage to resolve the conflicts on my local machine and push it again. I don't know what was the correct way, I was just trying several things :confused:  I would be very grateful @snicoll for explaining this to me again

**Comment by snicoll** [comment]
Okay, let’s follow up this week :)

**Review by adekimpianna — APPROVED** [review]

**Review by harunaltunhr — APPROVED** [review]
:100:

**Pull request merged**
