### PR TITLE
Add Yana bio

### LINKED ISSUE #6: Introduce Yana

### PR DESCRIPTION
**Pull request by Boam1994**
Hey guys, I made an interesting biology about Yana. Can you have a look and merge it please?

### CODE REVIEW

**Review by snicoll — CHANGES_REQUESTED** [review]
The history looks wrong to me. Can you please rework it so that there is a single commit with this task? Thanks!

**Comment by Boam1994** [comment]
Guys, I made changes but i don't know what else i have to do. May i have to make another pull request or resolve conflicts...?

**Comment by Boam1994** [comment]
i made changes & i don't know what to do now. May i have to creat another pull-request or resolve conflicts...?

**Review by snicoll — APPROVED** [review]

**Review by adekimpianna — COMMENTED** [review]
It looks correct for me, Boam, thanks!

**Pull request merged**
